### ISSUE TITLE
Question: how can i use this for multiple chats?

### ISSUE THREAD

**Issue by Mrs-Feathers** [mkdryden/telegram-stats-bot#24]
i'm using the docker version and its great for my community's general chat, but we have like ~30+ different topic chats and i need to get statistics on a few of them at the same time so i can better plan community events and stuff by seeing times people are active etc... how can i do this? should i list the CHAT_IDs? like -100XXXXXXX, -100XXXXXXX or should i copypaste the docker compose to run two bots on the same database?

**Comment by Mrs-Feathers** [comment]
in postgres i figured out using

    environment:
        - POSTGRES_MULTIPLE_DATABASES: db1,db2
        
allows me to use different databases in postgres, but running a couple instances of the bot for each room cause a weird update error

**Comment by mkdryden** [comment]
Currently there is not a way to make one bot instance handle multiple chats. It was always on the list, but I've been quite busy lately and haven't had the chance to look at it (and there are some changes to the Telegram bot API I need to double check). As far as I know, there should be no problem in using the same Postgres, but you need to make sure each bot service is pointing to the correct database (with the `POSTGRES_DB` environment var), so you might have:

```
  bot1:
    image: mkdryden/telegram-stats-bot:master
    depends_on:
      - db
    environment:
      TZ: "America/Toronto"
      BOT_TOKEN: 111111111:AAA-MpBVQ7i2cIRfwedfsfesdg6webc0r-Y
      CHAT_ID: 0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_DB: telegram_bot_1
  bot2:
    image: mkdryden/telegram-stats-bot:master
    depends_on:
      - db
    environment:
      TZ: "America/Toronto"
      BOT_TOKEN: 111111111:AAA-MpBVQ7i2cIRfwedfsfesdg6webc0r-Y
      CHAT_ID: 0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_DB: telegram_bot_2
```

From your config, I assume you are using the init script from [here](https://github.com/mrts/docker-postgresql-multiple-databases). Postgres 9.6 is probably too old to be supported, I think you need at least 12. I didn't look that close, but the script will probably work with later versions too.
